[package]
name = "onpeople-storage"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
aes.workspace = true
base64.workspace = true
cbc.workspace = true
chrono.workspace = true
directories.workspace = true
hex.workspace = true
keyring.workspace = true
parking_lot.workspace = true
pbkdf2.workspace = true
rusqlite.workspace = true
serde.workspace = true
serde_json.workspace = true
sha1.workspace = true
sha2.workspace = true
tempfile.workspace = true
thiserror.workspace = true
tracing.workspace = true
uuid.workspace = true
walkdir.workspace = true
onpeople-types = { path = "../onpeople-types" }

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61.2", features = ["Win32_Security_Cryptography", "Win32_Foundation", "Win32_System_Memory"] }

[lints]
workspace = true

