// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DesktopMethod } from "./DesktopMethod";
import type { JsonValue } from "./serde_json/JsonValue";

export type DesktopRequest = { protocolVersion: number, requestId: string, method: DesktopMethod, params: JsonValue, };
