// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppError } from "./AppError";
import type { JsonValue } from "./serde_json/JsonValue";

export type DesktopResponse = { protocolVersion: number, requestId: string, ok: boolean, result?: JsonValue | null, error?: AppError | null, };
