// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DesktopRecoveryRequired = { reason: string, afterSequence: number, oldestAvailableSequence: number | null, latestSequence: number, };
