// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DesktopMethod = "system.capabilities" | "runtime.status" | "runtime.start" | "runtime.stop" | "runtime.snapshot" | "runtime.diagnostics" | "event.replay" | "preferences.get" | "preferences.save" | "thread.list" | "scheduler.get" | "task.start" | "task.cancel" | "task.snapshot" | "task.resume" | "task.queue" | "task.queue.delete" | "task.steer" | "task.queue.steer" | "task.approval.resolve" | "task.input.resolve";
