// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

export type ExtensionsSnapshot = { skills: Array<JsonValue>, plugins: Array<JsonValue>, catalog: Array<JsonValue>, catalogStatus: JsonValue, activeIndustryPlugin: JsonValue | null, mcpServers: Array<JsonValue>, };
