// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MemoryState } from "./MemoryState";
import type { JsonValue } from "./serde_json/JsonValue";

export type MemorySaveResult = { entry: JsonValue, state: MemoryState, };
