// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProviderKind } from "./ProviderKind";

export type ModelDescriptor = { id: string, provider: ProviderKind, name: string, vision: boolean, reasoningEfforts: Array<string>, };
