// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProviderKind } from "./ProviderKind";
import type { JsonValue } from "./serde_json/JsonValue";

export type ProviderSettings = { kind: ProviderKind, name: string, protocol: string, baseUrl: string, model: string, vision: boolean, apiKeySet: boolean, extra: { [key in string]: JsonValue }, };
