// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SecretMetadata } from "./SecretMetadata";
import type { JsonValue } from "./serde_json/JsonValue";

export type SecretSaveResult = { secret: JsonValue, secrets: Array<SecretMetadata>, };
