// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TaskSnapshot } from "./TaskSnapshot";
import type { JsonValue } from "./serde_json/JsonValue";

export type TaskRecovery = { snapshot: TaskSnapshot, resumePayload: JsonValue, timeline: Array<JsonValue>, };
