// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TaskStartRequest = { threadId: string | null, text: string, cwd: string | null, workspaceMode: string | null, images: Array<string>, attachments: Array<string>, capability: string | null, mode: string | null, industryPlugin: string | null, model: string | null, reasoningEffort: string | null, };
