// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

export type TaskQueueSteerReceipt = { steered: boolean, accepted: boolean, id: string, threadId: string, taskId: string | null, lastSequence: number, result: JsonValue, };
