// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BrowserFrame = { routeId: string, sequence: bigint, width: number, height: number, scaleFactor: number, surfaceKind: string, surfaceHandle: string, damageRects: Array<[number, number, number, number]>, };
