// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BrowserAnnotation } from "./BrowserAnnotation";

export type BrowserAnnotationRequest = { routeId: string, annotation: BrowserAnnotation | null, annotationId: string | null, };
