// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BrowserAction = "navigate" | "back" | "forward" | "reload" | "captureVisualSnapshot" | "inspectDeveloperState" | "beginAnnotation" | "cancelAnnotation" | "sessionStatus" | "openSignIn" | "clearSession" | "clearAllData" | "clearSettingsData" | "fillSavedCredential" | "listImportProfiles" | "importProfile" | "attach" | "activateTab" | "detachTab" | "focus" | "downloads" | "showDownload" | "openExternal" | "zoom" | "recover";
