// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BrowserImportResult = { cookies: bigint, storageFiles: bigint, credentials: bigint, skipped: bigint, };
