// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BrowserProfile = { id: string, name: string, browser: string, path: string, lastUsedAt: string | null, };
