// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BrowserAnnotationRequest = { id: string, routeId: string, url: string, selector: string | null, rect: [number, number, number, number] | null, text: string, createdAt: string, };
