// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelDescriptor } from "./ModelDescriptor";
import type { JsonValue } from "./serde_json/JsonValue";

export type CloudAccountState = { signedIn: boolean, serviceUrl: string, account: JsonValue | null, group: JsonValue | null, models: Array<ModelDescriptor>, };
