// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ConnectorOauthCompleteRequest = { state: string, code: string | null, error: string | null, };
