// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

export type DesktopEvent = { protocolVersion: number, sequence: number, topic: string, emittedAt: string, threadId: string | null, taskId: string | null, payload: JsonValue, };
