// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Policy } from "./Policy";
import type { Preferences } from "./Preferences";
import type { ProviderSettings } from "./ProviderSettings";

export type EffectiveConfig = { source: string, cwd: string | null, provider: ProviderSettings, policy: Policy, preferences: Preferences, };
