// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DesktopEvent } from "./DesktopEvent";

export type EventReplay = { events: Array<DesktopEvent>, oldestAvailableSequence: number | null, latestSequence: number, nextSequence: number, requiresSnapshot: boolean, hasMore: boolean, };
