// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FileEntry = { name: string, path: string, kind: string, size: bigint | null, modifiedAt: string | null, hidden: boolean, };
