// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FilePreview = { opened: boolean, name: string, path: string, absolutePath: string, size: number, mimeType: string, kind: string, content: string | null, dataUrl: string | null, message: string | null, };
