// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GitFileState } from "./GitFileState";

export type GitState = { repository: boolean, root: string | null, branch: string | null, upstream: string | null, ahead: number, behind: number, files: Array<GitFileState>, };
