// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GoalStatus } from "./GoalStatus";

export type Goal = { id: string, threadId: string, objective: string, status: GoalStatus, tokenBudget: bigint | null, tokensUsed: bigint, timeUsedSeconds: bigint, createdAt: string, updatedAt: string, };
