// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

export type HookCreateRequest = { cwd: string, id: string | null, event: JsonValue | null, command: JsonValue | null, enabled: boolean | null, };
