// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MemoryLifecycle } from "./MemoryLifecycle";
import type { JsonValue } from "./serde_json/JsonValue";

export type MemoryState = { entries: Array<JsonValue>, candidates: Array<JsonValue>, lifecycle: MemoryLifecycle, settings: JsonValue, chatSettings: JsonValue, effectiveSettings: JsonValue, lastRecall: JsonValue, scopeCwd: string | null, };
