// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelDescriptor } from "./ModelDescriptor";
import type { JsonValue } from "./serde_json/JsonValue";

export type ModelCatalog = { models: Array<ModelDescriptor>, providers: Array<string>, errors: Array<JsonValue>, };
