// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Policy } from "./Policy";
import type { JsonValue } from "./serde_json/JsonValue";

export type PolicyState = { policy: Policy, audit: Array<JsonValue>, };
