// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProjectAction = { id: string, label: string, command: string, source: string, fingerprint: string, };
