// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProjectSummary = { path: string, name: string, pinned: boolean, hidden: boolean, threadCount: number, archivedThreadCount: number, updatedAt: string, };
