// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

export type ScheduledTaskRequest = { name: string, prompt: string, cwd: string, schedule: JsonValue, runtime: JsonValue, };
