// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

export type ScheduledTaskFromTextRequest = { name: string | null, prompt: string | null, text: string | null, cwd: string | null, schedule: JsonValue | null, runtime: JsonValue | null, };
