// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ScheduledRun } from "./ScheduledRun";
import type { ScheduledTask } from "./ScheduledTask";

export type SchedulerSnapshot = { tasks: Array<ScheduledTask>, runs: Array<ScheduledRun>, unread: number, };
