// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ShellAppUpdateDownload = { available: boolean, currentVersion: string | null, downloaded: boolean | null, version: string | null, bytes: number | null, };
