// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ShellAppUpdateCheck = { available: boolean, currentVersion: string, version: string | null, date: string | null, body: string | null, };
