// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StreamKind } from "./StreamKind";
import type { JsonValue } from "./serde_json/JsonValue";

export type StreamEnvelope = { sequence: bigint, kind: StreamKind, streamId: string, payload: JsonValue, terminal: boolean, };
