// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TaskState } from "./TaskState";

export type TaskHandle = { taskId: string, threadId: string, state: TaskState, acceptedAt: string, lastSequence: number, };
