// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TaskState } from "./TaskState";

export type TaskSnapshot = { taskId: string | null, threadId: string, state: TaskState, queuedMessages: number, pendingApprovals: number, lastSequence: number, };
