// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TaskState = "ready" | "running" | "waiting" | "queued" | "cancelling" | "cancelled" | "failed" | "unknown";
