// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ThreadSummary = { id: string, title: string, cwd: string, projectPath: string | null, status: string, pinned: boolean, archived: boolean, unread: boolean, model: string | null, reasoningEffort: string | null, workspaceMode: string, workspaceBaseCwd: string | null, createdAt: string, updatedAt: string, };
