// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProjectSummary } from "./ProjectSummary";
import type { ThreadSummary } from "./ThreadSummary";

export type ThreadList = { threads: Array<ThreadSummary>, projects: Array<ProjectSummary>, };
