// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WorktreeRequest = { root: string, path: string | null, branch: string | null, threadId: string | null, removeBranch: boolean, };
