// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CapabilityStatus } from "./CapabilityStatus";
import type { Goal } from "./Goal";
import type { Policy } from "./Policy";
import type { ProviderSettings } from "./ProviderSettings";

export type AgentStatus = { ready: boolean, runtime: string, version: string, defaultCwd: string, windowThreadId: string | null, goal: Goal | null, provider: ProviderSettings, policy: Policy, capabilities: { [key in string]: CapabilityStatus }, };
