// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AgentProfile = { id: string, name: string, role: string, model: string, effort: string, sandbox: string, instructions: string, builtIn: boolean, updatedAt: string | null, };
