// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AgentTask = { id: string, parentThreadId: string, agentId: string | null, title: string, prompt: string, status: string, result: string | null, createdAt: string, updatedAt: string, };
