// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AppUpdateState = { supported: boolean, status: string, currentVersion: string, availableVersion: string | null, progress: number | null, message: string | null, };
