// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BrowserTab } from "./BrowserTab";

export type BrowserState = { hostReady: boolean, 
/**
 * Shell-owned lifecycle state. The browser host itself only controls the
 * CEF-ready bit; the desktop shell adds starting/backoff/failed/crashed
 * states before publishing this DTO to the renderer.
 */
hostStatus: string, hostError?: string | null, hostErrorKind?: string | null, activeRouteId: string | null, tabs: Array<BrowserTab>, profilePath: string, };
