// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BrowserTab = { routeId: string, threadId: string, url: string, title: string, faviconUrl: string | null, loading: boolean, canGoBack: boolean, canGoForward: boolean, crashed: boolean, };
