// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ErrorCode = "INVALID_REQUEST" | "NOT_FOUND" | "CONFLICT" | "PERMISSION_DENIED" | "WORKSPACE_BOUNDARY" | "RUNTIME_UNAVAILABLE" | "RUNTIME_PROTOCOL" | "RUNTIME_TIMEOUT" | "PROCESS_FAILED" | "NETWORK" | "RATE_LIMITED" | "AUTHENTICATION" | "STORAGE" | "MIGRATION" | "KEYCHAIN" | "CANCELLED" | "UNSUPPORTED" | "INTERNAL";
