// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EventKind } from "./EventKind";
import type { JsonValue } from "./serde_json/JsonValue";

export type EventEnvelope = { sequence: number, kind: EventKind, emittedAt: string, windowLabel: string | null, threadId: string | null, payload: JsonValue, };
