// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EventKind = "agent" | "runtime" | "browser-state" | "browser-navigation" | "browser-preview" | "browser-new-tab" | "scheduler" | "scheduler-open" | "cloud-account" | "app-update" | "preferences" | "deep-link" | "command-palette" | "terminal-menu";
