// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LiveStatus = { available: boolean, voice: string, activeCallId: string | null, message: string | null, };
