// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MemoryRecord = { id: string, cwd: string, title: string, content: string, enabled: boolean, createdAt: string, updatedAt: string, };
