// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Preferences = { theme: string, density: string, reduceMotion: boolean, showComposerFooter: boolean, showSuggestions: boolean, defaultFileOpener: string, browserOpenLinks: string, browserEnabled: boolean, liveVoice: string, downloadDirectory: string | null, customInstructions: string, sidebarWidth: number, utilityWidth: number, terminalHeight: number, };
