// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

export type RuntimeDiagnostics = { state: string, pid: number | null, executable: string, version: string, restartCount: number, lastStartedAt: string | null, lastExitAt: string | null, lastError: string | null, events: Array<JsonValue>, };
