// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProviderKind } from "./ProviderKind";
import type { JsonValue } from "./serde_json/JsonValue";

export type SaveProviderRequest = { kind: ProviderKind, model: string, baseUrl: string, apiKey: string | null, threadId: string | null, extra: { [key in string]: JsonValue }, };
