// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

export type ScheduledTask = { id: string, name: string, prompt: string, cwd: string, enabled: boolean, schedule: JsonValue, runtime: JsonValue, nextRunAt: string | null, createdAt: string, updatedAt: string, };
