// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ScheduledRun = { id: string, taskId: string, status: string, startedAt: string, finishedAt: string | null, threadId: string | null, message: string | null, unread: boolean, };
