// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WorktreeSummary = { path: string, head: string, branch: string | null, bare: boolean, prunable: boolean, };
