const { contextBridge, ipcRenderer } = require("electron");

contextBridge.exposeInMainWorld("workbench", {
  agentStatus: () => ipcRenderer.invoke("agent:status"),
  sendPrompt: (payload) => ipcRenderer.invoke("agent:send", payload),
  pickImages: () => ipcRenderer.invoke("agent:image:pick"),
  pickAttachments: () => ipcRenderer.invoke("agent:attachment:pick"),
  pasteImage: () => ipcRenderer.invoke("agent:image:paste"),
  readGeneratedImage: (imagePath, threadId = null) => ipcRenderer.invoke("generated-image:read", imagePath, threadId),
  revealGeneratedImage: (imagePath, threadId = null) => ipcRenderer.invoke("generated-image:reveal", imagePath, threadId),
  copyGeneratedImage: (imagePath, threadId = null) => ipcRenderer.invoke("generated-image:copy", imagePath, threadId),
  setGoal: (payload) => ipcRenderer.invoke("agent:goal:set", payload),
  updateGoal: (threadId, action, value) => ipcRenderer.invoke("agent:goal:update", threadId, action, value),
  newTask: () => ipcRenderer.invoke("agent:new-task"),
  openTaskWindow: (threadId = null) => ipcRenderer.invoke("window:task:open", threadId),
  getPetState: () => ipcRenderer.invoke("pet:state"),
  togglePet: () => ipcRenderer.invoke("pet:toggle"),
  updatePetTask: (payload) => ipcRenderer.invoke("pet:update-task", payload),
  getProviderSettings: (type, threadId = null) => ipcRenderer.invoke("agent:provider:get", type, threadId),
  saveProvider: (settings) => ipcRenderer.invoke("agent:provider:save", settings),
  getCloudAccount: () => ipcRenderer.invoke("cloud:account:status"),
  loginCloudAccount: (payload) => ipcRenderer.invoke("cloud:account:login", payload),
  sendCloudRegistrationCode: (payload) => ipcRenderer.invoke("cloud:account:register-code", payload),
  registerCloudAccount: (payload) => ipcRenderer.invoke("cloud:account:register", payload),
  logoutCloudAccount: () => ipcRenderer.invoke("cloud:account:logout"),
  redeemCloudCode: (code) => ipcRenderer.invoke("cloud:account:redeem", code),
  openCloudConsole: () => ipcRenderer.invoke("cloud:account:open-console"),
  getAppUpdateState: () => ipcRenderer.invoke("app-update:state"),
  checkForAppUpdate: () => ipcRenderer.invoke("app-update:check"),
  downloadAppUpdate: () => ipcRenderer.invoke("app-update:download"),
  installAppUpdate: () => ipcRenderer.invoke("app-update:install"),
  openAppDownload: () => ipcRenderer.invoke("app-update:open-download"),
  listThreads: (filters) => ipcRenderer.invoke("threads:list", filters),
  resumeThread: (threadId) => ipcRenderer.invoke("threads:resume", threadId),
  forkThread: (threadId) => ipcRenderer.invoke("threads:fork", threadId),
  archiveThread: (threadId) => ipcRenderer.invoke("threads:archive", threadId),
  unarchiveThread: (threadId) => ipcRenderer.invoke("threads:unarchive", threadId),
  pinThread: (threadId, pinned) => ipcRenderer.invoke("threads:pin", threadId, pinned),
  markThreadUnread: (threadId, unread) => ipcRenderer.invoke("threads:unread", threadId, unread),
  renameThread: (threadId, name) => ipcRenderer.invoke("threads:rename", threadId, name),
  revealThread: (threadId) => ipcRenderer.invoke("threads:reveal", threadId),
  copyText: (value) => ipcRenderer.invoke("clipboard:write-text", value),
  readText: () => ipcRenderer.invoke("clipboard:read-text"),
  showTerminalContextMenu: (payload) => ipcRenderer.invoke("terminal:context-menu", payload),
  setTerminalFocused: (focused, processId = null) => ipcRenderer.send("terminal:focus-changed", Boolean(focused), processId),
  pickProject: (defaultPath) => ipcRenderer.invoke("projects:pick", defaultPath),
  updateProject: (projectPath, action, value = null) => ipcRenderer.invoke("projects:update", projectPath, action, value),
  revealProject: (projectPath) => ipcRenderer.invoke("projects:reveal", projectPath),
  archiveProjectTasks: (projectPath) => ipcRenderer.invoke("projects:archive-tasks", projectPath),
  startTerminal: (payload) => ipcRenderer.invoke("terminal:start", payload),
  readyTerminal: (processId) => ipcRenderer.invoke("terminal:ready", processId),
  writeTerminal: (processId, data) => ipcRenderer.invoke("terminal:write", processId, data),
  resizeTerminal: (processId, cols, rows) => ipcRenderer.invoke("terminal:resize", processId, cols, rows),
  terminateTerminal: (processId) => ipcRenderer.invoke("terminal:terminate", processId),
  getGitState: (cwd) => ipcRenderer.invoke("git:state", cwd),
  initGitRepository: (cwd) => ipcRenderer.invoke("git:init", cwd),
  getGitDiff: (cwd, filePath) => ipcRenderer.invoke("git:diff", cwd, filePath),
  getGitHunks: (cwd, filePath) => ipcRenderer.invoke("git:hunks", cwd, filePath),
  mutateGitHunk: (payload) => ipcRenderer.invoke("git:hunk:mutate", payload),
  mutateGit: (payload) => ipcRenderer.invoke("git:mutate", payload),
  commitGit: (cwd, message) => ipcRenderer.invoke("git:commit", cwd, message),
  pushGit: (cwd, remote) => ipcRenderer.invoke("git:push", cwd, remote),
  preparePullRequest: (cwd, base) => ipcRenderer.invoke("git:prepare-pr", cwd, base),
  startReview: (payload) => ipcRenderer.invoke("git:review", payload),
  submitReviewComments: (payload) => ipcRenderer.invoke("git:review-comments", payload),
  openEditor: (payload) => ipcRenderer.invoke("workspace:open-editor", payload),
  getRuntimeDiagnostics: () => ipcRenderer.invoke("runtime:diagnostics"),
  getRuntimeSnapshot: (threadId = null) => ipcRenderer.invoke("runtime:snapshot", threadId),
  restartRuntime: () => ipcRenderer.invoke("runtime:restart"),
  listExtensions: (cwd) => ipcRenderer.invoke("extensions:list", cwd),
  setSkillEnabled: (skillPath, enabled) => ipcRenderer.invoke("skills:set-enabled", skillPath, enabled),
  installPlugin: (plugin) => ipcRenderer.invoke("plugins:install", plugin),
  uninstallPlugin: (pluginId) => ipcRenderer.invoke("plugins:uninstall", pluginId),
  reloadMcp: () => ipcRenderer.invoke("mcp:reload"),
  discoverModels: () => ipcRenderer.invoke("models:discover"),
  validateModel: (providerType, modelId) => ipcRenderer.invoke("models:validate", providerType, modelId),
  listAgents: () => ipcRenderer.invoke("agents:list"),
  listAgentProfiles: () => ipcRenderer.invoke("agent-profiles:list"),
  saveAgentProfile: (profile) => ipcRenderer.invoke("agent-profiles:save", profile),
  deleteAgentProfile: (profileId) => ipcRenderer.invoke("agent-profiles:delete", profileId),
  spawnAgent: (payload) => ipcRenderer.invoke("agents:spawn", payload),
  messageAgent: (agentId, text) => ipcRenderer.invoke("agents:message", agentId, text),
  stopAgent: (agentId) => ipcRenderer.invoke("agents:stop", agentId),
  readAgent: (agentId) => ipcRenderer.invoke("agents:read", agentId),
  listWorktrees: (cwd) => ipcRenderer.invoke("worktrees:list", cwd),
  createWorktree: (payload) => ipcRenderer.invoke("worktrees:create", payload),
  handoffWorktree: (worktreePath) => ipcRenderer.invoke("worktrees:handoff", worktreePath),
  snapshotWorktree: (worktreePath) => ipcRenderer.invoke("worktrees:snapshot", worktreePath),
  removeWorktree: (worktreePath) => ipcRenderer.invoke("worktrees:remove", worktreePath),
  getContextState: () => ipcRenderer.invoke("context:state"),
  compactContext: () => ipcRenderer.invoke("context:compact"),
  steerTurn: (text) => ipcRenderer.invoke("context:steer", text),
  queueMessage: (text) => ipcRenderer.invoke("context:queue", text),
  getPolicy: () => ipcRenderer.invoke("policy:get"),
  savePolicy: (threadId, policy) => ipcRenderer.invoke("policy:save", threadId, policy),
  getEffectiveConfig: (payload) => ipcRenderer.invoke("config:effective", payload),
  listMemories: (cwd) => ipcRenderer.invoke("memories:list", cwd),
  saveMemory: (memory) => ipcRenderer.invoke("memories:save", memory),
  deleteMemory: (memoryId) => ipcRenderer.invoke("memories:delete", memoryId),
  saveMemorySettings: (settings) => ipcRenderer.invoke("memories:settings", settings),
  getUsageLedger: () => ipcRenderer.invoke("usage:snapshot"),
  saveUsagePrice: (key, price) => ipcRenderer.invoke("usage:price", key, price),
  listSecrets: () => ipcRenderer.invoke("secrets:list"),
  saveSecret: (secret) => ipcRenderer.invoke("secrets:save", secret),
  deleteSecret: (secretId) => ipcRenderer.invoke("secrets:delete", secretId),
  listHooks: (cwd) => ipcRenderer.invoke("hooks:list", cwd),
  createHook: (payload) => ipcRenderer.invoke("hooks:create", payload),
  listScheduledTasks: () => ipcRenderer.invoke("scheduler:list"),
  createScheduledTask: (payload) => ipcRenderer.invoke("scheduler:create", payload),
  updateScheduledTask: (taskId, patch) => ipcRenderer.invoke("scheduler:update", taskId, patch),
  deleteScheduledTask: (taskId) => ipcRenderer.invoke("scheduler:delete", taskId),
  runScheduledTask: (taskId) => ipcRenderer.invoke("scheduler:run-now", taskId),
  markScheduledNotificationsRead: (runId) => ipcRenderer.invoke("scheduler:mark-read", runId),
  interrupt: (threadId) => ipcRenderer.invoke("agent:interrupt", threadId),
  resolveApproval: (requestId, decision) => ipcRenderer.invoke("agent:approval", requestId, decision),
  navigate: (url) => ipcRenderer.invoke("browser:navigate", url),
  getQuickLauncherSuggestions: (cwd) => ipcRenderer.invoke("workspace:quick-suggestions", cwd),
  listProjectFiles: (cwd, relative) => ipcRenderer.invoke("workspace:files:list", cwd, relative),
  searchProjectFiles: (cwd, query) => ipcRenderer.invoke("workspace:files:search", cwd, query),
  getProjectActions: (cwd) => ipcRenderer.invoke("workspace:project-actions", cwd),
  authorizeProjectAction: (payload) => ipcRenderer.invoke("workspace:project-action:authorize", payload),
  openWorkspaceFile: (cwd, filePath) => ipcRenderer.invoke("browser:open-workspace-file", { cwd, path: filePath }),
  back: () => ipcRenderer.invoke("browser:back"),
  forward: () => ipcRenderer.invoke("browser:forward"),
  reload: () => ipcRenderer.invoke("browser:reload"),
  captureBrowserVisualSnapshot: () => ipcRenderer.invoke("browser:visual-snapshot"),
  inspectBrowserDeveloperState: () => ipcRenderer.invoke("browser:developer-inspect"),
  beginBrowserAnnotation: () => ipcRenderer.invoke("browser:annotation:begin"),
  cancelBrowserAnnotation: () => ipcRenderer.invoke("browser:annotation:cancel"),
  listBrowserAnnotations: (options) => ipcRenderer.invoke("browser:annotation:list", options),
  saveBrowserAnnotation: (draft) => ipcRenderer.invoke("browser:annotation:save", draft),
  deleteBrowserAnnotation: (annotationId) => ipcRenderer.invoke("browser:annotation:delete", annotationId),
  getBrowserSessionStatus: () => ipcRenderer.invoke("browser:session:status"),
  openBrowserSignIn: (providerId) => ipcRenderer.invoke("browser:session:sign-in", providerId),
  clearBrowserSession: (providerId) => ipcRenderer.invoke("browser:session:clear", providerId),
  clearAllBrowserData: () => ipcRenderer.invoke("browser:session:clear-all"),
  fillSavedBrowserCredential: () => ipcRenderer.invoke("browser:credentials:fill"),
  listBrowserImportProfiles: () => ipcRenderer.invoke("browser:profile-import:list"),
  importBrowserProfile: (payload) => ipcRenderer.invoke("browser:profile-import:run", payload),
  attachBrowser: (webContentsId) => ipcRenderer.invoke("browser:attach", webContentsId),
  onAgentEvent: (handler) => ipcRenderer.on("agent:event", (_event, value) => handler(value)),
  onTurnEvent: (handler) => ipcRenderer.on("runtime:event", (_event, value) => handler(value)),
  onBrowserState: (handler) => ipcRenderer.on("browser:state", (_event, value) => handler(value)),
  onAgentBrowserNavigation: (handler) => ipcRenderer.on("browser:agent-navigation", (_event, value) => handler(value)),
  onSchedulerUpdated: (handler) => ipcRenderer.on("scheduler:updated", (_event, value) => handler(value)),
  onSchedulerOpen: (handler) => ipcRenderer.on("scheduler:open", (_event, value) => handler(value)),
  onRuntimeUpdated: (handler) => ipcRenderer.on("runtime:updated", (_event, value) => handler(value)),
  onPetState: (handler) => ipcRenderer.on("pet:state", (_event, value) => handler(value)),
  onCloudAccountUpdated: (handler) => ipcRenderer.on("cloud:account:updated", (_event, value) => handler(value)),
  onAppUpdateState: (handler) => ipcRenderer.on("app-update:state", (_event, value) => handler(value)),
  onDeepLink: (handler) => ipcRenderer.on("app:deep-link", (_event, value) => handler(value)),
  onCommandPalette: (handler) => ipcRenderer.on("app:command-palette", () => handler()),
  onTerminalMenuAction: (handler) => ipcRenderer.on("terminal:menu-action", (_event, value) => handler(value)),
});
