name: Cross-platform checks

on:
  push:
  pull_request:

jobs:
  check:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-14
          - windows-2022
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "22.12"
          cache: npm
      - run: npm ci
      - run: npm run rebuild:native
      - run: npm run check
